version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
permissions:
  - object: /home/ec2-user/node/deploy_scripts/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - file
permissions:
  - object: /home/ec2-user/node/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/run.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate.sh
      timeout: 60
      runas: root
