#!/bin/bash
yum update -y
yum install ruby -y
yum install wget -y
yum install nmap-ncat -y
cd /home/ec2-user
wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
chmod +x ./install
./install auto
